Loja_Virtual_Django/carrinho/urls.py
from django.urls import path
from carrinho import views

app_name = 'carrinho'

urlpatterns = [
    path('', views.lista_produtos, name='lista_produtos'),
    path('atualiza_carrinho/', views.atualiza_carrinho, name='atualiza_carrinho'),
    path('exibe_carrinho/', views.exibe_carrinho, name='exibe_carrinho'),
    path('fecha_compra/', views.fecha_compra, name='fecha_compra'),
    path('<slug:slug_da_categoria>/', views.lista_produtos, name='lista_produtos_por_categoria'),
    path('<int:id>/<slug:slug_do_produto>/', views.exibe_produto, name='exibe_produto')
]

Loja_Virtual_Django/produto/urls.py
from django.urls import path

from produto import views

app_name = 'produto'

urlpatterns = [
    path('lista_produto/', views.lista_produto, name='lista_produto'),
    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('exibe_produto/<int:id>/', views.exibe_produto, name='exibe_produto'),
    path('edita_produto/<int:id>/', views.edita_produto, name='edita_produto'),
    path('remove_produto/', views.remove_produto, name='remove_produto')
]

Loja_Virtual_Django/projeto/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from projeto import views, settings

urlpatterns = [
    path('', lambda request: redirect('carrinho/')),
    path('carrinho/', include('carrinho.urls')),
    path('produto/', include('produto.urls')),
    path('admin/', admin.site.urls),
    path('autenticacao/', include('autenticacao.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Loja_Virtual_Django/carrinho/models.py
from django.db import models

# Create your models here.

Loja_Virtual_Django/carrinho/forms.py
from django import forms


class QuantidadeForm(forms.Form):

    produto_id = forms.CharField(widget=forms.HiddenInput())

    # <input type="hidden" name="produto_id" required="" id="id_produto_id" value="xxx">

    quantidade = forms.IntegerField(
        min_value=0,
        max_value=99,
        widget=forms.TextInput(attrs={'class': 'form-control btn-secondary quantidade',
                                      'style': 'text-align: center; background-color: #6c757d; width: 70px;',
                                      'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57)',
                                      'readonly': 'readonly'}),
        required=True
    )

    # <input type="text" name="quantidade" class="form-control btn-secondary quantidade"
    #        style="text-align:center; background-color: #6c757d; width: 70px;"
    #        readonly="readonly" required="" id="id_quantidade">

Loja_Virtual_Django/carrinho/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.signing import Signer
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from carrinho.carrinho import Carrinho
from carrinho.forms import QuantidadeForm
from categoria.models import Categoria
from produto.models import Produto

signer = Signer()

def lista_produtos(request, slug_da_categoria=None):
    categoria = None
    categorias = Categoria.objects.all().order_by('nome')
    lista_de_produtos = Produto.objects.filter(disponivel=True).order_by('nome')
    if slug_da_categoria:
        categoria = get_object_or_404(Categoria, slug=slug_da_categoria)
        lista_de_produtos = lista_de_produtos.filter(categoria=categoria).order_by('nome')

    paginator = Paginator(lista_de_produtos, 12)
    pagina = request.GET.get('pagina')
    try:
        produtos = paginator.page(pagina)
    except PageNotAnInteger:
        produtos = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        produtos = paginator.page(paginator.num_pages)

    carrinho = Carrinho(request)
    lista_de_forms = []
    for produto in produtos:
        qtd = carrinho.get_quantidade_total(produto.id)
        lista_de_forms.append(QuantidadeForm(initial={'quantidade': qtd, 'produto_id': signer.sign(produto.id)}))

    if request.is_ajax():
        return render(request, 'carrinho/pagina_de_produtos.html', {'listas': zip(produtos, lista_de_forms)})

    return render(request, 'carrinho/lista_produtos.html', {'categorias': categorias,
                                                            'listas': zip(produtos, lista_de_forms),
                                                            'categoria': categoria})

# def exibe_produto(request, id, slug_do_produto):
#     produto = get_object_or_404(Produto, id=id)
#
#     return render(request, 'carrinho/exibe_produto.html', {'produto': produto})

def exibe_produto(request, id, slug_do_produto):
   produto = get_object_or_404(Produto, id=id)
   carrinho = Carrinho(request)
   qtd = carrinho.get_quantidade_total(produto.id)
   form = QuantidadeForm(initial={'quantidade': qtd, 'produto_id': signer.sign(id)})

   return render(request, 'carrinho/exibe_produto.html', {'produto': produto, 'form': form})

def atualiza_carrinho(request):

    form = QuantidadeForm(request.POST)
    if form.is_valid():
        produto_id = signer.unsign(form.cleaned_data['produto_id'])
        quantidade = form.cleaned_data['quantidade']

        carrinho = Carrinho(request)
        if (quantidade == 0):
            carrinho.remover(produto_id)
            preco_total = 0.0
        else:
            carrinho.atualiza(produto_id, quantidade)
            preco_total = carrinho.get_preco_total(produto_id)

        qtd = carrinho.get_quantidade_carrinho()
        preco_carrinho = carrinho.get_preco_carrinho()

        print('***** id do produto = ' + produto_id +
              '  quantidade = ' + str(quantidade) +
              '  preço total do produto = ' + str(preco_total))
        print('***** qtd no carrinho = ' + str(qtd) +
              '  valor do carrinho = ' + str(preco_carrinho))

        return render(request, 'carrinho/resposta_ajax.html', {
            'preco_total': preco_total
        })
    else:
        raise ValueError('Ocorreu um erro inesperado ao adicionar um produto ao carrinho.')

def exibe_carrinho(request):
    carrinho = Carrinho(request)
    produtos_no_carrinho = carrinho.get_produtos()

    lista_de_forms = []
    for produto in produtos_no_carrinho:
        lista_de_forms.append(QuantidadeForm(
            initial={'quantidade': produto['quantidade'],
                     'produto_id': signer.sign(produto['id'])}))

    valor_do_carrinho = carrinho.get_preco_carrinho()

    return render(request, 'carrinho/produtos_no_carrinho.html', {
        'listas': zip(produtos_no_carrinho, lista_de_forms),
        'valor_do_carrinho': valor_do_carrinho
    })

def fecha_compra(request):
    return render(request, 'carrinho/fecha_compra.html')





















Loja_Virtual_Django/carrinho/templates/carrinho/exibe_produto.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Hortifruti
{% endblock %}

{% block corpo %}
   <div class="row mt-4" style="min-height: 379px">
      <div class="col-md-4 mb-4 mb-md-0">
         <img class="img-fluid rounded" style="width: 300px" src="{{ produto.imagem.url }}">
      </div>
      <div id="lista-produto" class="col-md-8">
         <h4>{{ produto.nome }} ({{ produto.descricao }})</h4>
         <h5><a style="text-decoration: none"
                href="{{ produto.categoria.get_absolute_url }}">{{ produto.categoria }}</a></h5>
         <p><strong>Preço: </strong>R$ {{ produto.preco }} por unidade.</p>

         <form class="form-inline" style="{% if form.quantidade.value == 0 %} display: none {% endif %}"
               method="POST" novalidate
               action="{% url 'carrinho:atualiza_carrinho' %}">
             {% csrf_token %}
             {{ form.produto_id }}
             <div class="input-group" style="width: 160px">
                 <div class="input-group-prepend">
                     <input type="button"
                            class="btn btn-secondary menos"
                            value="-">
                 </div>
                 {{ form.quantidade }}
                 <div class="input-group-append">
                     <input type="button"
                            class="btn btn-secondary mais"
                            value="+">
                 </div>
             </div>
         </form>
         <input type="button" class="btn btn-primary comprar"
                style="{% if form.quantidade.value > 0 %}display: none;{% endif %}width: 160px;"
                value="Comprar">
      </div>
   </div>
{% endblock %}

Loja_Virtual_Django/carrinho/templates/carrinho/fecha_compra.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Hortifruti
{% endblock %}

{% block corpo %}

   <div style="min-height: 382px"
        class="d-flex justify-content-center align-items-center">
      <h1>FIM</h1>
   </div>

{% endblock %}

Loja_Virtual_Django/carrinho/templates/carrinho/lista_produtos.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Hortifruti
{% endblock %}

{% block estilo %}
    <style>

    </style>
{% endblock %}

{% block corpo %}

    <div style="min-height: 387px">
       <div class="row">
          <div class="col-lg-2">
             <h5>Categorias</h5>
             <div class="nav flex-column nav-pills">
                <a class="nav-link {% if not categoria %}active{% endif %}" href="/">Todos</a>
                {% for cat in categorias %}
                   <a class="nav-link {% if cat == categoria %}active{% endif %}" href="{{ cat.get_absolute_url }}">
                      {{ cat.nome }}
                   </a>
                {% endfor %}
             </div>
          </div>

          <div class="col-lg-10">
             <h5>{% if not categoria %}Produtos{% else %}{{ categoria.nome }}{% endif %}</h5>
             <div id="lista-produto">
                {% include 'carrinho/pagina_de_produtos.html' %}
             </div>
          </div>
       </div>
    </div>

{% endblock %}

{% block domready %}
   var pagina = 1;
   var empty_page = false;
   var block_request = false;

   if ($(window).width() >= 1200)
      percentual = 22/100
   else if ($(window).width() >= 992)
      percentual = 30/100
   else if ($(window).width() >= 768)
      percentual = 40/100
   else if ($(window).width() >= 576)
      percentual = 60/100
   else
      percentual = 70/100

   $(window).scroll(function() {
      if  (($(document).height() - $(window).height() - $(window).scrollTop() < percentual * $(window).height())
           && empty_page == false && block_request == false) {
		   block_request = true;
		   pagina += 1;
		   $.get('?pagina=' + pagina, function(resposta) {
		      if(resposta == '') {
		         empty_page = true;
		      }
		      else {
               block_request = false;
               $('#lista-produto').append(resposta);
    	      }
         });
    	}
   });
{% endblock %}

Loja_Virtual_Django/carrinho/templates/carrinho/pagina_de_produtos.html
{% load static %}

<div class="row">
   {% for produto, form in listas %}
      <div class="col-xl-2 col-md-3 col-sm-4 col-6" style="padding-right: 0px; padding-left: 0px;">
         <div class="card border-0 mb-3" style="margin-right: 6px; margin-left: 6px;">
             <a href="{{ produto.get_absolute_url }}">
                <img class="card-img-top rounded" src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
             </a>
             <div class="card-body">
                 <h5 class="card-title">
                     <a href="{{ produto.get_absolute_url }}" style="text-decoration: none;">
                        {{ produto.nome }}
                     </a>
                 </h5>
                 <p class="card-text">{{ produto.descricao }}</p>
                 <p class="card-text font-weight-bold" style="color: #dc3545;">R$ {{ produto.preco }}</p>
             </div>
             <div class="card-footer border-0 p-0 mb-2">
                <form class="form-inline"
                      style="{% if form.quantidade.value == 0 %} display: none {% endif %}"
                      method="POST" novalidate
                      action="{% url 'carrinho:atualiza_carrinho' %}">
                   {% csrf_token %}
                   {{ form.produto_id }}
                   <div class="input-group w-100">
                      <div class="input-group-prepend">
                         <input type="button"
                                class="btn btn-secondary menos" value="-">
                      </div>
                      {{ form.quantidade }}
                      <div class="input-group-append">
                         <input type="button"
                                class="btn btn-secondary mais" value="+">
                      </div>
                   </div>
                </form>
                <input type="button" class="btn btn-primary comprar w-100"
                       style="{% if form.quantidade.value > 0 %} display: none {% endif %}"
                       value="Comprar">
             </div>
         </div>
      </div>
   {% endfor %}
</div>

Loja_Virtual_Django/carrinho/templates/carrinho/produtos_no_carrinho.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block titulo %}
    Hortifruti
{% endblock %}

{% block estilo %}
    <style>

    </style>
{% endblock %}

{% block corpo %}

   <div id="tabela" style="min-height: 387px">
      <div class="mt-3 mb-4">
         <h5 class="mb-2 text-primary">Meu Carrinho</h5>
      </div>

      <div class="table-responsive mb-3">
         <table class="table table-sm">
            <colgroup>
               <col width="40%">
               <col width="15%">
               <col width="15%">
               <col width="15%">
               <col width="15%">
            </colgroup>
            <thead>
               <tr>
                  <th class="text-center">Produto</th>
                  <th class="text-center">Preço Unitário</th>
                  <th class="text-center">Quantidade</th>
                  <th class="text-center">Preço Total</th>
                  <th class="text-center">Remover</th>
               </tr>
            </thead>
            <tbody>
               {% for item, form in listas %}
                  <tr>
                     <td class="text-left align-middle">
                        <div class="media">
                           <a href="{{ item.produto.get_absolute_url }}" tabindex="-1">
                              <img class="mr-3" style="width: 80px"
                                   src="{{ item.produto.imagem.url }}" alt="{{ item.produto.nome }}">
                           </a>
                           <div class="media-body">
                              <h6 class="mt-2">
                                 <a style="text-decoration: none" href="{{ item.produto.get_absolute_url }}"
                                    tabindex="-1">
                                    {{ item.produto.nome }}
                                 </a>
                              </h6>
                              <p class="mb-2">{{ item.produto.descricao }}</p>
                           </div>
                        </div>
                     </td>
                     <td class="text-center align-middle">
                        R$ {{ item.preco | intcomma }}
                     </td>
                     <td class="text-center align-middle">
                        <form class="mx-auto" style="width: 60px;"
                              action ="{% url 'carrinho:atualiza_carrinho' %}"
                              method ="POST" novalidate>
                           {% csrf_token %}
                           {{ form.produto_id }}
                           {{ form.quantidade }}
                        </form>
                     </td>
                     <td class="text-right pr-5 align-middle preco-total">
                        R$ {{ item.preco_total | intcomma }}
                     </td>
                     <td class="text-center align-middle">
                        <form style="margin-bottom: 0px;"
                              action ="{% url 'carrinho:atualiza_carrinho' %}"
                              method ="post" novalidate>
                           {% csrf_token %}
                           {{ form.produto_id }}
                           <button style="margin-top: 0px; margin-bottom: 0px; padding-top: 3px; padding-bottom: 3px; width: 40px"
                                   type="button" class="btn btn-sm btn-danger remover" tabindex="-1">
                              <img src="{% static 'images/skin/remove.png' %}">
                           </button>
                        </form>
                     </td>
                  </tr>
               {% endfor %}
               <tr>
                  <td colspan="3">
                     <strong style="margin-left: 10px">Total do carrinho ...</strong>
                  </td>
                  <td class="text-right pr-5">
                     <strong id="valor-do-carrinho">R$ {{ valor_do_carrinho | floatformat:2 | intcomma }}</strong>
                  </td>
                  <td></td>
               </tr>
            </tbody>
         </table>
      </div>
      <div class="d-flex justify-content-around mb-5">
         <a href="{% url 'carrinho:lista_produtos' %}" class="btn btn-success" style="width: 160px">
            Voltar às Compras
         </a>
         <a href="{% url 'carrinho:fecha_compra' %}" class="btn btn-success" style="width: 160px">
            Fechar Compra
         </a>
      </div>
   </div>

{% endblock %}

{% block domready %}

   $("input.quantidade").addClass("form-control-sm")
                        .removeClass("btn-secondary")
                        .removeAttr("readonly")
                        .css("background-color", "")

   $("#tabela").on("blur", "input.quantidade", function() {
      let valor = $(this).val()
      if (valor < 1 || valor > 99) {
         $(this).focus()
         return
      }

      let form = $(this).parent()
      let tr = form.parent().parent()
      let url = form.attr("action")
      let formData = form.serializeArray()
      $.post(url, formData, function(resposta) {
         let preco_total = $(resposta).find("#preco-total").text()
         let quantidade = $(resposta).find("#quantidade").text()
         let preco_carrinho = $(resposta).find("#preco-carrinho").text()

         tr.find("td.preco-total").text("R$ " + preco_total)
         $("#valor-do-carrinho").text("R$ " + preco_carrinho)

         if (quantidade == 1) {
            $("#total-1").text(quantidade + " item - R$ " + preco_carrinho)
         }
         else {
            $("#total-1").text(quantidade + " itens - R$ " + preco_carrinho)
         }
         $("#total-2").text("R$ " + preco_carrinho)
      })
   })

   $("#tabela").on("click", ".remover", function() {
      let form = $(this).parent()
      form.append('<input type="hidden" name="quantidade" value="0">')
      let tr = $(form).parent().parent()
      let url = $(form).attr('action')
      let formData = $(form).serializeArray()
      $.post(url, formData, function(resposta) {
         $(tr).fadeTo('slow', 0.3, function() {
            $(this).remove()

            let quantidade = $(resposta).find("#quantidade").text()
            let preco_carrinho = $(resposta).find("#preco-carrinho").text()

            $("#valor-do-carrinho").text("R$ " + preco_carrinho)

            if (quantidade == 1) {
               $("#total-1").text(quantidade + " item - R$ " + preco_carrinho)
            }
            else {
               $("#total-1").text(quantidade + " itens - R$ " + preco_carrinho)
            }
            $("#total-2").text("R$ " + preco_carrinho)
         })
      })
   })

{% endblock %}














Loja_Virtual_Django/carrinho/templates/carrinho/resposta_ajax.html
{% load humanize %}

<div>
   <div id="preco-total">{{ preco_total | intcomma }}</div>
   <div id="quantidade">{{ quantidade | intcomma }}</div>
   <div id="preco-carrinho">{{ preco_carrinho | floatformat:2 | intcomma }}</div>
</div>