Loja_Virtual_Django/produto/urls.py
from django.urls import path

from produto import views

app_name = 'produto'

urlpatterns = [
    path('lista_produto/', views.lista_produto, name='lista_produto'),
    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('exibe_produto/<int:id>/', views.exibe_produto, name='exibe_produto'),
    path('edita_produto/<int:id>/', views.edita_produto, name='edita_produto'),
    path('remove_produto/', views.remove_produto, name='remove_produto')
]

Loja_Virtual_Django/projeto/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from projeto import views, settings

urlpatterns = [
    path('', lambda request: redirect('carrinho/')),
    path('carrinho/', include('carrinho.urls')),
    path('produto/', include('produto.urls')),
    path('admin/', admin.site.urls),
    path('autenticacao/', include('autenticacao.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Loja_Virtual_Django/produto/models.py
from django.db import models
from django.urls import reverse

from categoria.models import Categoria

class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='produtos', on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=100, db_index=True, unique=True)
    descricao = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    # imagem = models.CharField(max_length=50, blank=True)
    imagem = models.ImageField(upload_to='images/')
    qtd_estoque = models.IntegerField()
    preco = models.DecimalField(max_digits=5, decimal_places=2)
    data_cadastro = models.DateField()
    disponivel = models.BooleanField(default=False)

    class Meta:
        db_table='produto'

    def __str__(self):
        return self.nome

    def get_disponivel(self):
        return "Sim" if self.disponivel else "Não"

    def get_absolute_url(self):
        return reverse('carrinho:exibe_produto', args=[self.id, self.slug])







Loja_Virtual_Django/produto/forms.py
from django import forms
from django.core.validators import RegexValidator

from categoria.models import Categoria
from produto.models import Produto
from projeto import settings


class PesquisaProdutoForm(forms.Form):

    nome = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
        required=False)

    # <input type="text" name="nome" id="id_nome" class="form-control form-control-sm" maxlength="100">


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = ('nome', 'descricao', 'categoria', 'data_cadastro', 'preco', 'qtd_estoque', 'imagem', 'disponivel')
        localized_fields = ('preco',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['nome'].error_messages={'required': 'Campo obrigatório.',
                                            'unique': 'Nome de produto duplicado.'}
        self.fields['nome'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['descricao'].error_messages={'required': 'Campo obrigatório'}
        self.fields['descricao'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['categoria'].error_messages={'required': 'Campo obrigatório'}
        self.fields['categoria'].queryset=Categoria.objects.all().order_by('nome')
        self.fields['categoria'].empty_label='--- Selecione uma categoria ---'
        self.fields['categoria'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['data_cadastro'].error_messages={'required': 'Campo obrigatório',
                                                     'invalid': 'Data inválida'}
        self.fields['data_cadastro'].input_formats=settings.DATE_INPUT_FORMATS
        self.fields['data_cadastro'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['preco'].min_value=0
        self.fields['preco'].error_messages={'required': 'Campo obrigatório.',
                                             'invalid': 'Valor inválido.',
                                             'max_digits': 'Mais de 5 dígitos no total.',
                                             'max_decimal_places': 'Mais de 2 dígitos decimais.',
                                             'max_whole_digits': 'Mais de 3 dígitos inteiros.'}
        self.fields['preco'].widget.attrs.update({
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })

        self.fields['qtd_estoque'].min_value=0
        self.fields['qtd_estoque'].error_messages={
            'required': 'Campo obrigatório',
            'min_value': 'A quantidade deve ser maior ou igual a zero.'
        }
        self.fields['qtd_estoque'].widget=forms.TextInput(attrs={
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })

        # self.fields['imagem'].error_messages={'required': 'Campo obrigatório'}
        # self.fields['imagem'].validators=[
        #     RegexValidator(regex='^[a-z]+\.(jpg|png|gif|bmp)$', message='Nome de imagem inválido.')]
        # self.fields['imagem'].widget.attrs.update({'class': 'form-control form-control-sm'})
        # self.fields['imagem'].required = True
        self.fields['imagem'].error_messages={'required': 'Campo obrigatório'}
        self.fields['imagem'].widget.attrs.update({'class': 'btn btn-outline-secondary btn-sm'})
        self.fields['imagem'].required = True

    # nome = forms.CharField(
    #     error_messages={'required': 'Campo obrigatório',
    #                     'unique': 'Nome de produto duplicado'},
    #     widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'})
    # )
    #
    # # <input type="text" name="nome" class="form-control form-control-sm" maxlength="100"
    # #        required="" id="id_nome">
    #
    # descricao = forms.CharField(
    #     error_messages={'required': 'Campo obrigatório'},
    #     widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'})
    # )
    #
    # # <input type="text" name="descricao" class="form-control form-control-sm" maxlength="100"
    # #        required="" id="id_descricao">
    #
    # categoria = forms.ModelChoiceField(
    #     error_messages={'required': 'Campo obrigatório'},
    #     queryset=Categoria.objects.all().order_by('nome'),
    #     empty_label="--- Selecione uma categoria ---",
    #     widget=forms.Select(attrs={'class': 'form-control form-control-sm'})
    # )
    #
    # # <select name="categoria" class="form-control form-control-sm" required="" id="id_categoria">
    # #     <option value="" selected>--- Selecione uma categoria ---</option>
    # #     <option value="1">Frutas</option>
    # #     <option value="2">Legumes</option>
    # #     <option value="3">Verduras</option>
    # # </select>
    #
    # data_cadastro = forms.DateField(
    #     error_messages={'required': 'Campo obrigatório.',
    #                     'invalid': 'Data inválida.'},
    #     input_formats=settings.DATE_INPUT_FORMATS,
    #     widget=forms.DateInput(attrs={'class': 'form-control form-control-sm'})
    # )
    #
    # # <input type="text" name="data_cadastro" class="form-control form-control-sm" required=""
    # #        id="id_data_cadastro">
    #
    # preco = forms.DecimalField(
    #     localize=True,
    #     min_value=0,
    #     error_messages={'required': 'Campo obrigatório.',
    #                     'invalid': 'Preço inválido.',
    #                     'min_value': 'O preço deve ser maior ou igual a zero.',
    #                     'max_digits': 'Mais de 5 dígitos no total.',
    #                     'max_decimal_places': 'Mais de 2 dígitos decimais.',
    #                     'max_whole_digits': 'Mais de 3 dígitos inteiros.'},
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control form-control-sm',
    #         'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
    #     })
    # )
    #
    # Beware that not all browsers support entering localized numbers in number input types.
    # Django itself avoids using them for fields having their localize property set to True.
    # # <input type="text" name="preco" class="form-control form-control-sm"
    # #        onkeypress="return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44"
    # #        required="" id="id_preco">
    #
    # qtd_estoque = forms.IntegerField(
    #     min_value=0,
    #     error_messages={'required': 'Campo obrigatório.',
    #                     'min_value': 'A quantidade deve ser maior ou igual a zero.'},
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control form-control-sm',
    #         'onkeypress': 'return event.charCode >= 48 && event.charCode <= 57'
    #     })
    # )
    #
    # # <input type="text" name="qtd_estoque" class="form-control form-control-sm"
    # #        onkeypress="return event.charCode >= 48 && event.charCode <= 57"
    # #        required="" id="id_qtd_estoque">
    #
    # imagem= forms.CharField(
    #     error_messages={'required': 'Campo obrigatório.'},
    #     validators=[RegexValidator(regex='^[a-z]+\.(jpg|png|gif|bmp)$', message='Nome de imagem inválido.')],
    #     widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '50'})
    # )
    #
    # # <input type="text" name="imagem" class="form-control form-control-sm" maxlength="50"
    # #        required="" id="id_imagem">
    #
    # # disponivel = forms.BooleanField(
    # #     widget=forms.CheckboxInput(),
    # #     required=False
    # # )

Loja_Virtual_Django/produto/views.py
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaultfilters import slugify

from produto.forms import PesquisaProdutoForm, ProdutoForm
from produto.models import Produto

# @login_required(login_url='/autenticacao/login')
# @staff_member_required(login_url='/autenticacao/login')
# @user_passes_test(lambda u: u.is_superuser)
# @user_passes_test(lambda u: u.is_staff)
def lista_produto(request):
    form = PesquisaProdutoForm(request.GET)
    if form.is_valid():
        nome = form.cleaned_data['nome']
        lista_de_produtos = Produto.objects\
                                   .filter(nome__icontains=nome)\
                                   .order_by('nome')

        paginator = Paginator(lista_de_produtos, 3)
        pagina = request.GET.get('pagina')
        page_obj = paginator.get_page(pagina)

        print(lista_de_produtos)
        print(page_obj)

        return render(request, 'produto/pesquisa_produto.html', { 'produtos': page_obj,
                                                                  'form': form,
                                                                  'nome': nome })


        # # Cria um objeto paginator que irá provocar a execução de uma query que irá
        # # retornar apenas os produtos de uma determinada página.
        # paginator = Paginator(lista_de_produtos, 6)  # Mostra 6 produtos por página
        # pagina = request.GET.get('pagina')
        # try:
        #     produtos = paginator.page(pagina)
        # except PageNotAnInteger:
        #     # If page is not an integer, deliver first page.
        #     produtos = paginator.page(1)
        # except EmptyPage:
        #     # If the request is AJAX and the page is out of range return an empty page
        #     if request.is_ajax():
        #         return HttpResponse('')
        #     # If page is out of range (e.g. 9999), deliver last page of results.
        #     produtos = paginator.page(paginator.num_pages)
        #
        # if request.is_ajax():
        #     return render(request, 'vendas/produto/lista_ajax.html', {'produtos': produtos})
        #
        # return render(request, 'vendas/produto/lista.html', {'categoria': categoria,
        #                                                      'categorias': categorias,
        #                                                      'produtos': produtos})
    else:
        raise ValueError('Ocorreu um erro inesperado ao tentar recuperar um produto.')


# @user_passes_test(lambda u: u.is_staff)
def cadastra_produto(request):

    if request.POST:
        produto_id = request.session.get('produto_id')
        print('produto_id na sessão = ' + str(produto_id))
        if produto_id:
            produto = get_object_or_404(Produto, pk=produto_id)
            produto_form = ProdutoForm(request.POST, request.FILES, instance=produto)
        else:
            produto_form = ProdutoForm(request.POST, request.FILES)

        if produto_form.is_valid():
            produto = produto_form.save(commit=False)
            produto.slug = slugify(produto.nome)
            produto.save()
            if produto_id:
                messages.add_message(request, messages.INFO, 'Produto alterado com sucesso!')
                del request.session['produto_id']
            else:
                messages.add_message(request, messages.INFO, 'Produto cadastrado com sucesso!')

            return redirect('produto:exibe_produto', id=produto.id)
    else:
        # if 'produto_id' in request.session:
        #     del request.session['produto_id']
        try:
            del request.session['produto_id']
        except KeyError:
            pass
        produto_form = ProdutoForm()

    return render(request, 'produto/cadastra_produto.html', {'form': produto_form})


# @user_passes_test(lambda u: u.is_staff)
def exibe_produto(request, id):
    produto = get_object_or_404(Produto, pk=id)
    request.session['produto_id_del'] = id
    return render(request, 'produto/exibe_produto.html', {'produto': produto})


# @user_passes_test(lambda u: u.is_staff)
def edita_produto(request, id):
    produto = get_object_or_404(Produto, pk=id)
    produto_form = ProdutoForm(instance=produto)
    request.session['produto_id'] = id
    return render(request, 'produto/cadastra_produto.html', {'form': produto_form})


# @user_passes_test(lambda u: u.is_staff)
def remove_produto(request):
    produto_id = request.session.get('produto_id_del')
    produto = get_object_or_404(Produto, id=produto_id)
    produto.imagem.delete()
    produto.delete()
    del request.session['produto_id_del']
    messages.add_message(request, messages.INFO, 'Produto removido com sucesso.')
    return render(request, 'produto/exibe_produto.html', {'produto': produto})





Loja_Virtual_Django/produto/templates/produto/cadastra_produto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Cadastro de Produtos
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Cadastro de Produtos</h5>
      <hr class='mt-0'>
   </div>

   <form action="{% url 'produto:cadastra_produto' %}" method="POST" class="pb-4"
         enctype="multipart/form-data" novalidate style="min-height: 330px">
      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_nome" class="col-xl-2 font-weight-bold">Nome</label>
               <div class="col-xl-10">
                  {{ form.nome }}
                  {# <input type="text" name="nome" maxlength="100" required="" id="id_nome"> #}
                  {% if form.nome.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.nome.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_descricao" class="col-xl-3 font-weight-bold">Descrição</label>
               <div class="col-xl-9">
                  {{ form.descricao }}
                  {# <input type="text" name="descricao" maxlength="100" required="" id="id_descricao"> #}
                  {% if form.descricao.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.descricao.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_categoria" class="col-xl-2 font-weight-bold">Categoria</label>
               <div class="col-xl-10">
                  {{ form.categoria }}
                  {% comment %}
                     <select name="categoria" required="" id="id_categoria">
                        <option value="" selected="">---------</option>
                        <option value="1">Frutas</option>
                        <option value="2">Legumes</option>
                        <option value="3">Verduras</option>
                     </select>
                  {% endcomment %}
                  {% if form.categoria.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.categoria.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_data_cadastro" class="col-xl-3 font-weight-bold">Data Cadastro</label>
               <div class="col-xl-9">
                  {{ form.data_cadastro }}
                  {# <input type="text" name="data_cadastro" required="" id="id_data_cadastro"> #}
                  {% if form.data_cadastro.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.data_cadastro.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_preco" class="col-xl-2 font-weight-bold">Preço</label>
               <div class="col-xl-10">
                  {{ form.preco }}
                  {# <input type="number" name="preco" value="0" step="0.01" required="" id="id_preco"> #}
                  {% if form.preco.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.preco.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_qtd_estoque" class="col-xl-3 font-weight-bold">Estoque</label>
               <div class="col-xl-9">
                  {{ form.qtd_estoque }}
                  {# <input type="number" name="qtd_estoque" value="0" required="" id="id_qtd_estoque"> #}
                  {% if form.qtd_estoque.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.qtd_estoque.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_imagem" class="col-xl-2 font-weight-bold">Imagem</label>
               <div class="col-xl-10">
                  {{ form.imagem }}
                  {# <input type="text" name="imagem" maxlength="50" id="id_imagem"> #}
                  {% if form.imagem.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.imagem.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <div class="offset-xl-3 col-xl-9">
                  <div class="form-check pl-0 mt-xl-0 mt-2">
                     {{ form.disponivel }}
                     {# <input type="checkbox" name="disponivel" id="id_disponivel"> #}
                     <label for="id_disponivel" class="form-check-label">Disponível?</label>
                  </div>
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-5">
         <div class="col-xl-6">
            <div class="row">
               <div class="col-xl-10 offset-xl-2">
                  {% csrf_token %}
                  <button id="botao" type="submit" class="btn btn-primary">
                     {% if 'produto_id' in request.session %}
                        <img src="{% static 'images/skin/database_edit.png' %}"> Alterar
                     {% else %}
                        <img src="{% static 'images/skin/database_add.png' %}"> Cadastrar
                     {% endif %}
                  </button>
               </div>
            </div>
         </div>
      </div>

   </form>

{% endblock %}

{% block domready %}

   $('#id_data_cadastro').datepicker({
       changeMonth: true,
       changeYear: true,
       yearRange: "-3:+0",
       dateFormat: 'dd/mm/yy',
       dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
       dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
       dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
       monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
       monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
       nextText: 'Próximo',
       prevText: 'Anterior',
       showOn: 'focus',
   })

   $('#id_data_cadastro').mask('00/00/0000')

{% endblock %}

Loja_Virtual_Django/produto/templates/produto/exibe_produto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Cadastro de Produtos
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Cadastro de Produtos</h5>
      <hr class='mt-0'>
   </div>

   <div style="min-height: 330px">
      {% if messages %}
         <div class="mb-3">
            {% for message in messages %}
               <ul class="list-group rounded">
                  <li style="padding-top: 7px; padding-bottom: 7px"
                      class="list-group-item list-group-item-info">
                     {{ message }}
                  </li>
               </ul>
            {% endfor %}
         </div>
      {% endif %}

      <div class="row mb-3">
         <div class="col-lg-3 col-md-4">
            {% if produto.imagem %}
               <img class="mr-3" style="width: 210px"
                    src="{{produto.imagem.url}}" alt="{{ produto.nome }}">
            {% else %}
               <div class="text-md-center mb-md-0 mb-2">
                  Imagem não disponível
               </div>
            {% endif %}
         </div>
         <div class="col-lg-9 col-md-8">
            <div class="row">
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Categoria</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ produto.categoria }}</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Nome</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ produto.nome }} ({{ produto.descricao }})</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Preço</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ produto.preco }}</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Estoque</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ produto.qtd_estoque }}</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Data Cadastro</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ produto.data_cadastro | date:'d/m/Y' }}</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Disponível</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ produto.get_disponivel }}</div>
            </div>
         </div>
      </div>

      {% if produto.id %}
         <div class="form-group row">
            <div class="col-12">
               <div class="form-inline">
                  <a href="{% url 'produto:edita_produto' produto.id %}" class="btn btn-primary mr-3">
                     <img src="{% static 'images/skin/database_edit.png' %}" /> Editar
                  </a>

                  <form action="{% url 'produto:remove_produto' %}" method="POST">
                     {% csrf_token %}
                     <button type="submit" class="btn btn-danger">
                        <img src="{% static 'images/skin/database_delete.png' %}"> Remover
                     </button>
                  </form>
               </div>
            </div>
         </div>
      {% endif %}
   </div>
{% endblock %}












Loja_Virtual_Django/produto/templates/produto/pesquisa_produto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Pesquisa de Produtos
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Pesquisa de Produtos</h5>
      <hr class='mt-0'>
   </div>

   <form action="" method ='GET' class="mb-4">
      <div class='form-group row' style='margin-bottom: 10px;'>
         <label for='id_nome' class='col-lg-2 col-form-label font-weight-bold'>
            Nome
         </label>
         <div class='col-lg-10'>
            {{ form.nome }}
            <!--
            <input type='text' name='nome' id='id_nome' class='form-control form-control-sm' maxlength='100'>
            -->
         </div>
      </div>
      <div class='form-group row'>
         <div class="col-lg-10 offset-lg-2">
            <button type='submit' class='btn btn-primary'>
               <div class="d-flex align-items-center">
                  <img src="{% static 'images/skin/binoculo.png' %}" class="mr-2">Pesquisar
               </div>
            </button>
         </div>
      </div>
   </form>

   <div style="min-height: 212px">
      {% if produtos %}
         <h5 class="mb-3">Lista de Produtos</h5>
         <table style='width:100%'
                class='table table-striped table-sm table-bordered table-responsive mb-4'>
            <thead>
               <tr>
                  <th class='text-center'>Imagem</th>
                  <th class='text-center'>Categoria</th>
                  <th class='text-center'>Nome/Descrição</th>
                  <th class="text-center">Disponível</th>
                  <th class='text-center'>Data de Cadastro</th>
                  <th class="text-center">Quantidade</th>
                  <th class="text-center">Preço Unitário</th>
               </tr>
            </thead>
            <tbody>
               {% for produto in produtos %}
                  <tr>
                     <td width="10%" class="text-center align-middle">
                        <img style="width:80px"
                             src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
                     </td>
                     <td width="10%" class="text-center align-middle">
                        {{ produto.categoria }}
                     </td>
                     <td width="35%" class="align-middle">
                        <a href="{% url 'produto:exibe_produto' produto.id %}">
                           {{ produto.nome }} ({{ produto.descricao }})
                        </a>
                     </td>
                     <td width="10%" class="text-center align-middle">
                        {{ produto.get_disponivel }}
                     </td>
                     <td width="15%" class="text-center align-middle">
                        {{ produto.data_cadastro | date:'d/m/Y' }}
                     </td>
                     <td width="10%" class="text-right align-middle pr-3">
                        {{ produto.qtd_estoque }}
                     </td>
                     <td width="15%" class="text-right align-middle pr-3">
                        R$ {{ produto.preco }}
                     </td>
                  </tr>
               {% endfor %}
            </tbody>
         </table>

         <div style='font-size: 14px; margin-bottom: 28px'>
            {% if produtos.has_other_pages %}
               <ul class='pagination'>
                  {% if produtos.has_previous %}
                     <li class='page-item'><a class='page-link' href='?pagina={{ produtos.previous_page_number }}&nome={{nome}}'>Anterior</a></li>
                  {% else %}
                     <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Anterior</a></li>
                  {% endif %}
                  {% for i in produtos.paginator.page_range %}
                     {% if produtos.number == i %}
                        <li class='page-item active'><a class='page-link' href='#'>{{ i }} </a></li>
                     {% else %}
                        <li class='page-item'><a class='page-link' href='?pagina={{ i }}&nome={{nome}}'>{{ i }}</a></li>
                     {% endif %}
                  {% endfor %}
                  {% if produtos.has_next %}
                     <li class='page-item'><a class='page-link' href='?pagina={{ produtos.next_page_number }}&nome={{nome}}'>Próxima</a></li>
                  {% else %}
                     <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Próxima</a></li>
                  {% endif %}
               </ul>
            {% endif %}
         </div>
      {% endif %}
   </div>

{% endblock %}